title: Mohan Giri
#logo: /assets/img/channels4_profile.jpg
description: Physicist with expertise in ultrafast spectroscopy and computational methods to explore material properties. Proficient in spectroscopy techniques, optical systems, and advanced data analysis including applications of machine learning. Passionate about scientific research, teaching, and leveraging computational tools to unravel complex physical systems.
#show_downloads: true
theme: jekyll-theme-minimal
